services:
  backend:
    tty: true
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && npx prisma db seed  && npm run start:dev"
    build:
      context: ../
      dockerfile: configs/Dockerfile.backend
    ports:
      - "${PORT}:${PORT}" 
      - "${PRISMA_STUDIO_PORT}:${PRISMA_STUDIO_PORT}"
    volumes:
      - ${DEV_BACKEND_SRC_PATH}/src:/usr/app/src
      - ${DEV_BACKEND_SRC_PATH}/prisma:/usr/app/prisma
      - ${DEV_BACKEND_SRC_PATH}/test:/usr/app/test
    environment:
      PORT: ${PORT}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_URL: ${DATABASE_CLIENT}://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_NAME}
      NODE_ENV: ${NODE_ENV}
      # This is for hot reloading between windows-linux machines
      WDS_SOCKET_HOST: ${WDS_SOCKET_HOST}
      CHOKIDAR_USEPOLLING: ${CHOKIDAR_USEPOLLING}
      TS_NODE_DEV: ${TS_NODE_DEV}
      WATCHPACK_POLLING: ${WATCHPACK_POLLING}
    networks:
      - network_db
  db:
    image: postgres:14.1-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}" 
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - network_db

networks:
  network_db:
volumes:
  db:
