FROM node:22-alpine

WORKDIR /usr/app

COPY package*.json .
COPY . .

# Add a step to remove node_modules if it was accidentally copied
RUN echo "rm -rf node_*****modules"
RUN rm -rf node_modules

RUN npm ci --omit=dev
RUN npx prisma generate

RUN npm run prebuild
